/* Browser QA against the real game UI. Test hooks are injected in-memory only. */
const {chromium}=require(process.env.LWH_PLAYWRIGHT||'playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const root=path.resolve(__dirname,'..'),web=path.join(root,'app/src/main/assets/www');
const out=path.join(__dirname,'captures'),results=path.join(__dirname,'results');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(results,{recursive:true});
// Captures are generated evidence for this run; do not package obsolete artwork.
for(const name of fs.readdirSync(out))if(name.endsWith('.png'))fs.unlinkSync(path.join(out,name));
const log={checks:[],runs:[],screens:[],errors:[]};
function ok(name,value){assert(value,name);log.checks.push(name)}
const hooks=`window.QA={state:()=>state,cities,careers,reasons,carPool,roadEvents,blankState,blankTripStats,show,renderPrep,renderSupplies,renderRoadHud,renderTrade,showQuiet,triggerEvent,driveLeg,endGame,openTripLog,renderCarAd,visitSeller,sellerState,makeOffer,save,loadLifetime,resolveCustomCity,refineRouteMiles,choiceCost,sfx,showOffers,audio:()=>({state:audioCtx?.state,soundOn,master:master?.gain.value,step:musicStep}),audioNodes:()=>({audioCtx,master,musicGain,sfxGain}),fixture:(patch)=>{state={...state,...patch};if(patch.cityData)restoreSavedCities();ensureTripStats();}};`;
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(req.url.split('?')[0]);if(pathname==='/')pathname='/index.html';const file=path.resolve(web,'.'+pathname);if(!file.startsWith(web+path.sep)){res.writeHead(403).end();return;}try{let body=fs.readFileSync(file);if(file.endsWith('game.js'))body=body.toString().replace('boot();',hooks+'\nboot();');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'text/html');res.end(body)}catch{res.writeHead(404).end()}});
const seedScript=`(()=>{let seed=92813;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};})();`;
async function capture(page,name){await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll(".screen.active img")].every(i=>i.complete&&i.naturalWidth>0&&(!i.dataset.requestedSrc||i.getAttribute('src')===i.dataset.requestedSrc)));await page.waitForTimeout(260);await page.screenshot({path:path.join(out,name+'.png')});const audit=await page.evaluate(()=>{const active=document.querySelector('.screen.active');return {screen:active?.id,overflow:document.documentElement.scrollWidth>innerWidth+1,images:[...active.querySelectorAll('img')].map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0})),buttons:[...active.querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.hidden).map(b=>({id:b.id,text:b.textContent.trim(),width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height}))}});assert(!audit.overflow,name+' horizontal overflow');assert(audit.images.every(x=>x.loaded),name+' missing artwork: '+JSON.stringify(audit.images));assert(audit.buttons.every(b=>b.height>=40&&b.width>=30),name+' undersized controls');log.screens.push({name,...audit})}
async function startLife(page,career='SOFTWARE ENGINEER',reason='JUST LEAVE'){
 if(await page.locator('#newGameBtn').isVisible())await page.click('#newGameBtn');else await page.click('#againBtn');await page.locator('#careerGrid button').filter({hasText:career}).click();await page.locator('#reasonGrid button').filter({hasText:reason}).click();await page.click('#beginLifeBtn');await page.waitForSelector('#prepScreen.active');
}
async function buyReliable(page){await page.locator('#prepActions button').filter({hasText:'CLAIM RELOCATION'}).click();await page.click('#openMarketBtn');for(let i=0;i<12;i++){if((await page.locator('#carAd').innerText()).includes('FAMILY LX'))break;await page.click('#nextCarBtn')}await page.click('#visitSellerBtn');{const size=page.viewportSize();await page.setViewportSize({width:1920,height:1080});await capture(page,'store-seller');await page.setViewportSize(size);}await page.click('#inspectBtn');await page.click('#testDriveBtn');await page.click('#mechanicCheckBtn');await page.click('#negotiateBtn');await page.locator('#offerButtons button').first().click();if(await page.locator('#buyCarBtn').isDisabled()){await page.click('#walkAwayBtn');await page.click('#nextCarBtn');await page.click('#visitSellerBtn')}await page.click('#buyCarBtn');await page.waitForSelector('#supplyScreen.active');for(const b of await page.locator('#supplyGrid button').all())if(await b.isEnabled())await b.click();}
async function doRun(page,fail=false){await startLife(page);await buyReliable(page);await page.click('#departBtn');if(!fail){const size=page.viewportSize();await page.setViewportSize({width:1920,height:1080});await capture(page,'store-drive');await page.setViewportSize(size);}const events=[];let n=0;while(n++<250){const state=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));if(state.ended){log.runs.push({type:fail?'failure':'success',steps:n,ending:state.ending,stats:state.stats,cash:state.cash,events});ok((fail?'failure':'successful')+' complete UI run',fail?state.ending.kicker!=='YOU MADE IT':state.ending.kicker==='YOU MADE IT');return;}if(state.currentEvent){const labels=await page.locator('#eventChoices button:enabled').allTextContents();let preferred=fail?['KEEP DRIVING','KEEP GOING','SKIP IT']:['FILL TANK','GET A ROOM','DINER','FULL REPAIR','STOP NOW','PULL OVER','STAY ON HIGHWAY','USE PAPER ATLAS','NO THANKS','SAVE THE MONEY','REPAIR','PAY','FIND COVER'];let label=preferred.map(p=>labels.find(l=>l.startsWith(p))).find(Boolean)||labels[0];assert(label,'available choice');events.push({id:state.currentEvent,choice:label,miles:state.distance,cash:state.cash});await page.locator('#eventChoices button').filter({hasText:label}).first().click()}else await page.click('#driveLegBtn');}throw Error('Run did not finish')}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.LWH_CHROME?{executablePath:process.env.LWH_CHROME}:{})});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(seedScript);const page=await context.newPage();page.on('pageerror',e=>log.errors.push(e.message));
 // Deterministic offline baseline; dedicated routing checks below exercise network responses.
 await page.route(/router\.project-osrm\.org/,r=>r.abort());
 await page.goto(url);await capture(page,'title-portrait');await startLife(page);const base=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await capture(page,'prep-portrait');
 await page.evaluate(()=>{const before=QA.state().cash;document.querySelector('#assetList .mini-actions button:last-child').click();window.pawnResult={before,after:QA.state().cash,sold:QA.state().assets.filter(a=>a.sold).length}});ok('finite possession sale changes money once',await page.evaluate(()=>pawnResult.after>pawnResult.before&&pawnResult.sold===1));await page.reload();await page.click('#resumeBtn');ok('possession sale survives close/reopen',await page.evaluate(()=>QA.state().assets.filter(a=>a.sold).length===1));
 await buyReliable(page);const purchased=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await page.click('#departBtn');await capture(page,'drive-portrait');
 await page.evaluate(()=>QA.triggerEvent(QA.roadEvents.find(e=>e.id==='motel')));await page.reload();await page.click('#resumeBtn');ok('pending event restored on reopen',await page.evaluate(()=>QA.state().currentEvent==='motel'&&document.querySelectorAll('#eventChoices button').length===3));
 const pending=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await page.setViewportSize({width:844,height:390});ok('rotation preserves pending state',await page.evaluate(s=>JSON.stringify(QA.state())===JSON.stringify(s),pending));await capture(page,'motel-landscape');
 await page.evaluate(()=>QA.fixture({cash:0}));await page.evaluate(()=>QA.triggerEvent(QA.roadEvents.find(e=>e.id==='motel')));ok('cannot obtain a free motel room',await page.locator('#eventChoices button').first().isDisabled());
 await page.evaluate(s=>{QA.fixture({...s,departed:true,cash:6000});QA.renderRoadHud();QA.show('roadScreen')},purchased);
 // Every major scene family in both phone orientations. These are explicit QA fixtures,
 // separate from the complete UI runs below.
 const screenPlan=[['title',()=>QA.show('titleScreen')],['setup',()=>{QA.show('setupScreen')}],['prep',()=>{QA.renderPrep();QA.show('prepScreen')}],['classifieds',()=>{QA.renderCarAd();QA.show('carMarketScreen')}],['seller',()=>{QA.visitSeller()}],['negotiation',()=>{QA.visitSeller();QA.showOffers()}],['supplies',()=>{QA.renderSupplies();QA.show('supplyScreen')}],['drive',()=>{QA.fixture({currentEvent:null,scene:'drive'});QA.showQuiet();QA.renderRoadHud();QA.show('roadScreen')}],...['fuel','food','motel','repair','restarea','heat'].map(id=>[id,`QA.show('roadScreen');QA.triggerEvent(QA.roadEvents.find(e=>e.id==='${id}'))`]),['trade',()=>{QA.fixture({undergroundUnlocked:false});QA.renderTrade();QA.show('tradeScreen')}],['underground',()=>{QA.fixture({undergroundUnlocked:true});QA.renderTrade();QA.show('tradeScreen')}],['trip',()=>{QA.openTripLog('current','roadScreen')}],['lifetime',()=>{QA.openTripLog('lifetime','roadScreen')}],['arrival',()=>{QA.fixture({ended:false});QA.endGame('YOU MADE IT','WELCOME HOME.','The journey worked.')}],['failure',()=>{QA.fixture({ended:false,stats:QA.blankTripStats()});QA.endGame('STRANDED','THE ROAD GOES ON WITHOUT YOU.','You ran out of fuel.')}]];
 for(const [orientation,size] of [['portrait',{width:390,height:844}],['landscape',{width:844,height:390}]]){await page.setViewportSize(size);for(const [name,fn] of screenPlan){await page.evaluate(fn);await capture(page,name+'-'+orientation);const anchors={setup:'#onlineRoutes',prep:'#prepActions',negotiation:'#offerButtons',supplies:'#departBtn',underground:'#undergroundPanel .kicker',trip:'#tripBackBtn',lifetime:'#tripBackBtn'};if(anchors[name]){await page.locator(anchors[name]).scrollIntoViewIfNeeded();await capture(page,name+'-details-'+orientation);await page.evaluate(()=>{document.querySelectorAll('.content-scroll').forEach(x=>x.scrollTop=0);window.scrollTo(0,0)})}}}

 // Inspect every fictional listing's art crop in both orientations.
 const vehicleIds=await page.evaluate(()=>QA.carPool.map(c=>c.id));
 for(const [orientation,size] of [['portrait',{width:390,height:844}],['landscape',{width:844,height:390}]]){
  await page.setViewportSize(size);
  for(const id of vehicleIds){await page.evaluate(id=>{QA.fixture({listings:QA.carPool.map(c=>({...c,sold:false})),carIndex:QA.carPool.findIndex(c=>c.id===id)});QA.renderCarAd();QA.show('carMarketScreen')},id);await capture(page,'vehicle-'+id+'-'+orientation);}
 }
 ok('all ten fictional vehicles load in both orientations',vehicleIds.length===10);
 // Controlled refueling through actual choices, including restart and the next leg.
 await page.evaluate(s=>{QA.fixture({...s,departed:true,ended:false,distance:200,totalMiles:1000,fuel:10,cash:500,pendingLegMiles:50,lastFuelVisitMiles:null,stats:QA.blankTripStats()});QA.show('roadScreen');QA.triggerEvent(QA.roadEvents.find(e=>e.id==='fuel'));},purchased);
 await page.locator('#eventChoices button').filter({hasText:/^FILL TANK/}).click();
 ok('full refill sets tank to full and records actual gallons cost',await page.evaluate(()=>Math.abs(QA.state().fuel-100)<1e-8&&Math.abs(QA.state().stats.fuelSpent-QA.state().car.tank*.9*4)<.011));
 await page.click('#driveLegBtn');
 ok('refill permits planned leg without an immediate repeat fuel event',await page.evaluate(()=>QA.state().distance===250&&QA.state().currentEvent!=='fuel'&&Math.abs(QA.state().fuel-(100-50/(QA.state().car.mpg*QA.state().car.tank)*100))<1e-8));
 await page.evaluate(()=>{QA.fixture({fuel:0,cash:5,pendingLegMiles:62,currentEvent:null});QA.triggerEvent(QA.roadEvents.find(e=>e.id==='fuel'))});
 ok('cash-limited refill discloses amount and insufficient range before purchase',await page.locator('#eventBody').innerText().then(t=>t.includes('PARTIAL REFILL ONLY')&&t.includes('1.25 gallons')&&t.includes('WARNING')));
 await capture(page,'partial-refill-landscape');await page.locator('#eventChoices').scrollIntoViewIfNeeded();await capture(page,'partial-refill-details-landscape');
 await page.locator('#eventChoices button').filter({hasText:/^PARTIAL REFILL/}).click();
 await page.reload();await page.click('#resumeBtn');
 ok('partial refill money and fuel survive reopening',await page.evaluate(()=>QA.state().cash===0&&Math.abs(QA.state().fuel/100*QA.state().car.tank-1.25)<1e-8));
 await page.evaluate(s=>{QA.fixture({...s,departed:true,ended:false,currentEvent:null,distance:0,totalMiles:1000,fuel:1,cash:0,pendingLegMiles:50,fuelStopDeclined:false,stats:QA.blankTripStats()});QA.showQuiet();QA.renderRoadHud();QA.show('roadScreen')},purchased);
 await page.click('#driveLegBtn');await page.locator('#eventChoices button').filter({hasText:'KEEP GOING'}).click();await page.click('#driveLegBtn');
 ok('running dry accounts for remaining gallons, distance and time',await page.evaluate(()=>{const s=QA.state();return s.ended&&s.fuel===0&&Math.abs(s.distance-s.car.tank*.01*s.car.mpg)<1e-8&&Math.abs(s.stats.gallonsUsed-s.car.tank*.01)<1e-8&&s.stats.driveHours>0}));
 // Three attempts are a hard cap even when a seller still has patience.
 await page.evaluate(s=>{QA.fixture({...s,car:{...QA.carPool.find(c=>c.id==='family')},carIndex:s.listings.findIndex(c=>c.id==='family'),cash:6000,ended:false,sellers:{}});QA.visitSeller();let seller=QA.sellerState(QA.state().car);seller.patience=4;window.savedRandom=Math.random;Math.random=()=>.999;},purchased);
 for(let n=0;n<3;n++){if(await page.locator('#negotiateBtn').isEnabled())await page.click('#negotiateBtn');await page.locator('#offerButtons button').nth(1).click();}
 ok('negotiation stops at three attempts',await page.evaluate(()=>QA.sellerState(QA.state().car).attempts===3&&document.getElementById('negotiateBtn').disabled));await page.evaluate(()=>Math.random=window.savedRandom);
 // Inspecting a car does not make it owned after reopening.
 await page.reload();await page.click('#resumeBtn');ok('unbought seller car stays unbought on resume',await page.evaluate(()=>document.getElementById('sellerScreen').classList.contains('active')&&!QA.state().car.boughtPrice));
 // Migrate an earlier branded-car save without losing its journey or seller history.
 await page.evaluate(s=>{const old={...s,version:3,departed:true,condition:63,distance:321,log:['Bought a Toyota Camry LE.'],car:{...s.car,id:'camry',n:'Toyota Camry LE'},listings:s.listings.map(c=>c.id==='family'?{...c,id:'camry',n:'Toyota Camry LE'}:c),sellers:{camry:{attempts:2,patience:1}},currentEvent:null};QA.fixture(old);QA.save();},purchased);
 await page.reload();await page.click('#resumeBtn');
 ok('legacy vehicle save preserves money, condition, mileage and seller attempts',await page.evaluate(s=>{const current=QA.state();return current.car.id==='family'&&current.car.n==='Family LX'&&current.cash===s.cash&&current.condition===63&&current.distance===321&&current.sellers.family.attempts===2&&!current.sellers.camry&&current.log[0]==='Bought a Family LX.'&&JSON.stringify(current.inventory)===JSON.stringify(s.inventory)},purchased));
 await capture(page,'legacy-save-resumed');
 // Natural market transactions: acquire gray stock, sell it, discover the contact,
 // then buy and sell fictional underground goods and verify Heat/accounting.
 await page.evaluate(s=>{QA.fixture({...s,departed:true,ended:false,cash:6000,currentMarket:null,lastMarketKey:'',underworldScore:0,undergroundUnlocked:false,heat:0,cargo:{}});QA.renderTrade();QA.show('tradeScreen')},purchased);
 const gray=page.locator('#tradeList .market-row').filter({hasText:/BOOTLEG CONCERT TEES|UNLABELED ELECTRONICS/}).first();
 ok('gray goods generated for discovery test',await gray.count()===1);
 const beforeTrade=await page.evaluate(()=>({cash:QA.state().cash,good:{...QA.state().currentMarket.goods.find(g=>g.gray)},trades:QA.state().stats.marketTrades}));await gray.getByText('BUY 1',{exact:true}).click();await gray.getByText('SELL 1',{exact:true}).click();
 ok('legal/gray trading tracks cash, stock and transactions',await page.evaluate(b=>{const s=QA.state(),g=s.currentMarket.goods.find(g=>g.id===b.good.id);return s.cash===b.cash-b.good.buy+b.good.sell&&g.supply===b.good.supply-1&&g.demand===b.good.demand-1&&(s.cargo[g.id]||0)===0&&s.stats.marketTrades===b.trades+2&&s.underworldScore===2},beforeTrade));
 await page.locator('#contactPanel button').click();ok('underground discoverable from gray trading',await page.evaluate(()=>QA.state().undergroundUnlocked));
 const heatBefore=await page.evaluate(()=>QA.state().heat);await page.locator('#undergroundList .market-row').first().getByText('BUY 1',{exact:true}).click();await page.locator('#undergroundList .market-row').first().getByText('SELL 1',{exact:true}).click();ok('underground transactions raise Heat and record P&L',await page.evaluate(h=>QA.state().heat>h&&QA.state().stats.undergroundSpent>0&&QA.state().stats.undergroundEarned>0,heatBefore));
 await capture(page,'underground-transactions');
 // Custom city persistence and routing-provider failure are deterministic network tests.
 await page.route(/photon\.komoot\.io/,r=>r.fulfill({json:{features:[{properties:{name:'Havana',state:'Illinois',countrycode:'US'},geometry:{coordinates:[-90.06,40.3]}}]}}));
 const custom=await page.evaluate(()=>QA.resolveCustomCity('Havana, IL'));ok('arbitrary U.S. city resolution',custom.n==='Havana, Illinois'&&custom.lat===40.3);
 await page.evaluate(c=>{QA.cities.push(c);QA.fixture({origin:QA.cities.length-1});QA.save()},custom);await page.reload();await page.click('#resumeBtn');ok('custom-city route survives browser restart',await page.evaluate(()=>QA.cities[QA.state().origin].n==='Havana, Illinois'));
 await page.unroute(/photon\.komoot\.io/);await page.route(/photon\.komoot\.io/,r=>r.fulfill({json:{features:[{properties:{name:'Paris',countrycode:'FR'},geometry:{coordinates:[2.3,48.8]}}]}}));ok('foreign geocoding result rejected',await page.evaluate(async()=>await QA.resolveCustomCity('Paris')===null));
 await page.evaluate(()=>QA.fixture({departed:false}));await page.unroute(/router\.project-osrm\.org/);await page.route(/router\.project-osrm\.org/,r=>r.fulfill({json:{routes:[{distance:160934.4,legs:[{steps:[{distance:160934.4,name:'US 24',maneuver:{type:'continue'}}]}]}]}}));await page.evaluate(()=>QA.refineRouteMiles());ok('road route mileage and instructions applied',await page.evaluate(()=>QA.state().totalMiles===100&&QA.state().routeSteps[0].name==='US 24'));
 await page.unroute(/router\.project-osrm\.org/);await page.route(/router\.project-osrm\.org/,r=>r.abort());
 // Audio signal, mute persistence and actual pause/resume lifecycle.
 await page.evaluate(()=>QA.show('titleScreen'));await page.click('#soundBtn');await page.click('#soundBtn');await page.waitForTimeout(500);
 ok('music starts after user interaction',await page.evaluate(()=>QA.audio().state==='running'&&QA.audio().step>0));
 const audioSignal=await page.evaluate(async()=>{const {audioCtx,master}=QA.audioNodes();const analyser=audioCtx.createAnalyser();analyser.fftSize=2048;master.connect(analyser);let peak=0;for(let i=0;i<15;i++){await new Promise(r=>setTimeout(r,30));const data=new Float32Array(2048);analyser.getFloatTimeDomainData(data);peak=Math.max(peak,...data.map(Math.abs))}master.disconnect(analyser);return peak});ok('audible synthesized signal without clipping',audioSignal>.001&&audioSignal<.98);
 const effects=await page.evaluate(async()=>{const {audioCtx,master,musicGain}=QA.audioNodes(),level=musicGain.gain.value;musicGain.gain.value=0;const analyser=audioCtx.createAnalyser();analyser.fftSize=2048;master.connect(analyser);const samples={};await new Promise(r=>setTimeout(r,200));for(const kind of ['ui','cash','car','bad','cop','win']){QA.sfx(kind);let peak=0;for(let i=0;i<24;i++){await new Promise(r=>setTimeout(r,10));const data=new Float32Array(2048);analyser.getFloatTimeDomainData(data);peak=Math.max(peak,...data.map(Math.abs))}samples[kind]=peak;await new Promise(r=>setTimeout(r,250));}master.disconnect(analyser);musicGain.gain.value=level;return samples});log.audio={musicPeak:audioSignal,effectPeaks:effects};ok('all six sound effects produce unclipped audio',Object.values(effects).every(peak=>peak>.001&&peak<.98));
 await page.evaluate(()=>LWHLifecycle.pause());ok('background audio suspends',await page.evaluate(()=>QA.audio().state==='suspended'));await page.evaluate(()=>LWHLifecycle.resume());await page.waitForTimeout(100);ok('foreground audio resumes',await page.evaluate(()=>QA.audio().state==='running'));
 await page.click('#soundBtn');await page.reload();ok('mute survives close/reopen',await page.evaluate(()=>!QA.audio().soundOn));
 // Actual rendered animation frames, plus reduced-motion behavior.
 await page.setViewportSize({width:844,height:390});await page.evaluate(s=>{QA.fixture({...s,departed:true,ended:false,scene:'drive',weather:'CLEAR'});QA.showQuiet();QA.renderRoadHud();QA.show('roadScreen')},purchased);
 const movingFrames=[];for(let n=0;n<3;n++){await page.waitForTimeout(190);movingFrames.push(await page.locator('.road-art-scene').screenshot({path:path.join(out,`motion-drive-${n}.png`)}));}
 ok('rendered road motion changes between frames',!movingFrames[0].equals(movingFrames[1])&&!movingFrames[1].equals(movingFrames[2]));
 await page.evaluate(()=>{QA.fixture({weather:'HEAVY RAIN'});QA.renderRoadHud()});await capture(page,'rain-landscape');ok('weather caption follows changing road weather',await page.locator('#sceneCaption').innerText()==='ON THE ROAD / HEAVY RAIN');
 await page.emulateMedia({reducedMotion:'reduce'});ok('reduced motion disables animated layers',await page.evaluate(()=>getComputedStyle(document.querySelector('.road-motion img')).animationName==='none'));await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>QA.show('titleScreen'));await page.click('#aboutBtn');ok('help and privacy dialog opens and closes',await page.locator('#aboutDialog').isVisible());await page.screenshot({path:path.join(out,'about-landscape.png')});await page.locator('#aboutDialog form button').click();
 // All screen families fit both compact phone orientations; inspect additional
 // small/large layouts for the most demanding screens.
 for(const size of [{width:360,height:800},{width:800,height:360},{width:1280,height:720}]){await page.setViewportSize(size);for(const name of ['title','seller','drive','trip']){const entry=screenPlan.find(x=>x[0]===name);if(name!=='title')await page.evaluate(s=>QA.fixture({...s,departed:true,ended:false}),purchased);await page.evaluate(entry[1]);await capture(page,`${name}-${size.width}x${size.height}`)}}
 // Explicit offline control: setup works without making a provider request.
 await page.evaluate(()=>QA.show('titleScreen'));await page.click('#newGameBtn');await page.uncheck('#onlineRoutes');let offlineRequests=0;const requestListener=r=>{if(/photon\.komoot|router\.project-osrm/.test(r.url()))offlineRequests++};page.on('request',requestListener);await page.locator('#careerGrid button').filter({hasText:'SOFTWARE ENGINEER'}).click();await page.locator('#reasonGrid button').filter({hasText:'JUST LEAVE'}).click();await page.click('#beginLifeBtn');await page.waitForSelector('#prepScreen.active');await page.waitForTimeout(300);ok('offline setup never contacts routing providers',offlineRequests===0&&await page.evaluate(()=>QA.state().onlineRoutes===false&&QA.state().routeDistanceSource==='estimate'));page.off('request',requestListener);await page.reload();ok('offline preference persists',!await page.locator('#onlineRoutes').isChecked());
 // Full playthroughs use UI controls only; no state injection or synthetic results.
 await context.clearCookies();await page.evaluate(()=>localStorage.clear());await page.goto(url);await page.setViewportSize({width:1080,height:1920});await capture(page,'store-title');await page.setViewportSize({width:390,height:844});await doRun(page,false);await capture(page,'success-run-ending');await page.click('#endTripReportBtn');await capture(page,'success-final-report');await page.setViewportSize({width:1920,height:1080});await capture(page,'store-trip');await page.setViewportSize({width:390,height:844});const lifetime=await page.evaluate(()=>QA.loadLifetime());ok('successful run counted exactly once',lifetime.runs===1&&lifetime.successes===1);await page.reload();await page.click('#resumeBtn');ok('completed run resumes final report without recounting',await page.evaluate(()=>QA.loadLifetime().runs===1));await doRun(page,true);await capture(page,'failure-run-ending');ok('failure lifetime accounting',await page.evaluate(()=>QA.loadLifetime().runs===2&&QA.loadLifetime().failures===1));
 ok('no JavaScript runtime exceptions',log.errors.length===0);
 fs.writeFileSync(path.join(results,'browser-qa.json'),JSON.stringify(log,null,2));await browser.close();server.close();console.log(JSON.stringify({checks:log.checks.length,screens:log.screens.length,runs:log.runs.map(r=>({type:r.type,miles:r.stats.milesDriven,ending:r.ending.kicker})),errors:log.errors}));
})().catch(e=>{log.errors.push(e.stack);fs.writeFileSync(path.join(results,'browser-qa.json'),JSON.stringify(log,null,2));console.error(e);server.close();process.exit(1)});
