/* Browser QA against the real game UI. Test hooks are injected in-memory only. */
const {chromium}=require(process.env.LWH_PLAYWRIGHT||'playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const root=path.resolve(__dirname,'..'),web=path.join(root,'app/src/main/assets/www');
const out=path.join(__dirname,'captures'),results=path.join(__dirname,'results');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(results,{recursive:true});
const log={checks:[],runs:[],screens:[],errors:[]};
function ok(name,value){assert(value,name);log.checks.push(name)}
const hooks=`window.QA={state:()=>state,cities,careers,reasons,carPool,roadEvents,blankState,blankTripStats,show,renderPrep,renderSupplies,renderRoadHud,renderTrade,showQuiet,triggerEvent,driveLeg,endGame,openTripLog,renderCarAd,visitSeller,sellerState,makeOffer,save,loadLifetime,resolveCustomCity,refineRouteMiles,choiceCost,audio:()=>({state:audioCtx?.state,soundOn,master:master?.gain.value,step:musicStep}),fixture:(patch)=>{state={...state,...patch};ensureTripStats();}};`;
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(req.url.split('?')[0]);if(pathname==='/')pathname='/index.html';const file=path.resolve(web,'.'+pathname);if(!file.startsWith(web+path.sep)){res.writeHead(403).end();return;}try{let body=fs.readFileSync(file);if(file.endsWith('game.js'))body=body.toString().replace('boot();',hooks+'\nboot();');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'text/html');res.end(body)}catch{res.writeHead(404).end()}});
const seedScript=`(()=>{let seed=92813;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};})();`;
async function capture(page,name){await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.querySelectorAll(".screen.active img")].every(i=>i.complete&&i.naturalWidth>0));await page.waitForTimeout(260);await page.screenshot({path:path.join(out,name+'.png')});const audit=await page.evaluate(()=>{const active=document.querySelector('.screen.active');return {screen:active?.id,overflow:document.documentElement.scrollWidth>innerWidth+1,images:[...active.querySelectorAll('img')].map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0})),buttons:[...active.querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.hidden).map(b=>({id:b.id,text:b.textContent.trim(),width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height}))}});assert(!audit.overflow,name+' horizontal overflow');assert(audit.images.every(x=>x.loaded),name+' missing artwork: '+JSON.stringify(audit.images));assert(audit.buttons.every(b=>b.height>=40&&b.width>=30),name+' undersized controls');log.screens.push({name,...audit})}
async function startLife(page,career='SOFTWARE ENGINEER',reason='JUST LEAVE'){
 if(await page.locator('#newGameBtn').isVisible())await page.click('#newGameBtn');else await page.click('#againBtn');await page.locator('#careerGrid button').filter({hasText:career}).click();await page.locator('#reasonGrid button').filter({hasText:reason}).click();await page.click('#beginLifeBtn');await page.waitForSelector('#prepScreen.active');
}
async function buyReliable(page){await page.locator('#prepActions button').filter({hasText:'CLAIM RELOCATION'}).click();await page.click('#openMarketBtn');for(let i=0;i<12;i++){if((await page.locator('#carAd').innerText()).includes('CAMRY'))break;await page.click('#nextCarBtn')}await page.click('#visitSellerBtn');await page.click('#inspectBtn');await page.click('#testDriveBtn');await page.click('#mechanicCheckBtn');await page.click('#negotiateBtn');await page.locator('#offerButtons button').first().click();if(await page.locator('#buyCarBtn').isDisabled()){await page.click('#walkAwayBtn');await page.click('#nextCarBtn');await page.click('#visitSellerBtn')}await page.click('#buyCarBtn');await page.waitForSelector('#supplyScreen.active');for(const b of await page.locator('#supplyGrid button').all())if(await b.isEnabled())await b.click();}
async function doRun(page,fail=false){await startLife(page);await buyReliable(page);await page.click('#departBtn');const events=[];let n=0;while(n++<250){const state=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));if(state.ended){log.runs.push({type:fail?'failure':'success',steps:n,ending:state.ending,stats:state.stats,cash:state.cash,events});ok((fail?'failure':'successful')+' complete UI run',fail?state.ending.kicker!=='YOU MADE IT':state.ending.kicker==='YOU MADE IT');return;}if(state.currentEvent){const labels=await page.locator('#eventChoices button:enabled').allTextContents();let preferred=fail?['KEEP DRIVING','KEEP GOING','SKIP IT']:['FILL TANK','GET A ROOM','DINER','FULL REPAIR','STOP NOW','PULL OVER','STAY ON HIGHWAY','USE PAPER ATLAS','NO THANKS','SAVE THE MONEY','REPAIR','PAY','FIND COVER'];let label=preferred.map(p=>labels.find(l=>l.startsWith(p))).find(Boolean)||labels[0];assert(label,'available choice');events.push({id:state.currentEvent,choice:label,miles:state.distance,cash:state.cash});await page.locator('#eventChoices button').filter({hasText:label}).first().click()}else await page.click('#driveLegBtn');}throw Error('Run did not finish')}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.LWH_CHROME?{executablePath:process.env.LWH_CHROME}:{})});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(seedScript);const page=await context.newPage();page.on('pageerror',e=>log.errors.push(e.message));
 // Deterministic offline baseline; dedicated routing checks below exercise network responses.
 await page.route(/router\.project-osrm\.org/,r=>r.abort());
 await page.goto(url);await capture(page,'title-portrait');await startLife(page);const base=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await capture(page,'prep-portrait');
 await page.evaluate(()=>{const before=QA.state().cash;document.querySelector('#assetList .mini-actions button:last-child').click();window.pawnResult={before,after:QA.state().cash,sold:QA.state().assets.filter(a=>a.sold).length}});ok('finite possession sale changes money once',await page.evaluate(()=>pawnResult.after>pawnResult.before&&pawnResult.sold===1));await page.reload();await page.click('#resumeBtn');ok('possession sale survives close/reopen',await page.evaluate(()=>QA.state().assets.filter(a=>a.sold).length===1));
 await buyReliable(page);const purchased=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await page.click('#departBtn');await capture(page,'drive-portrait');
 await page.evaluate(()=>QA.triggerEvent(QA.roadEvents.find(e=>e.id==='motel')));await page.reload();await page.click('#resumeBtn');ok('pending event restored on reopen',await page.evaluate(()=>QA.state().currentEvent==='motel'&&document.querySelectorAll('#eventChoices button').length===3));
 const pending=await page.evaluate(()=>JSON.parse(JSON.stringify(QA.state())));await page.setViewportSize({width:844,height:390});ok('rotation preserves pending state',await page.evaluate(s=>JSON.stringify(QA.state())===JSON.stringify(s),pending));await capture(page,'motel-landscape');
 await page.evaluate(()=>QA.fixture({cash:0}));await page.evaluate(()=>QA.triggerEvent(QA.roadEvents.find(e=>e.id==='motel')));ok('cannot obtain a free motel room',await page.locator('#eventChoices button').first().isDisabled());
 await page.evaluate(s=>{QA.fixture({...s,departed:true,cash:6000});QA.renderRoadHud();QA.show('roadScreen')},purchased);
 // Every major scene family in both phone orientations. These are explicit QA fixtures,
 // separate from the complete UI runs below.
 const screenPlan=[['setup',()=>{QA.show('setupScreen')}],['prep',()=>{QA.renderPrep();QA.show('prepScreen')}],['autotrader',()=>{QA.renderCarAd();QA.show('carMarketScreen')}],['seller',()=>{QA.visitSeller()}],['supplies',()=>{QA.renderSupplies();QA.show('supplyScreen')}],['drive',()=>{QA.fixture({currentEvent:null,scene:'drive'});QA.showQuiet();QA.renderRoadHud();QA.show('roadScreen')}],...['fuel','food','motel','repair','restarea','heat'].map(id=>[id,`QA.show('roadScreen');QA.triggerEvent(QA.roadEvents.find(e=>e.id==='${id}'))`]),['trade',()=>{QA.fixture({undergroundUnlocked:false});QA.renderTrade();QA.show('tradeScreen')}],['underground',()=>{QA.fixture({undergroundUnlocked:true});QA.renderTrade();QA.show('tradeScreen')}],['trip',()=>{QA.openTripLog('current','roadScreen')}],['lifetime',()=>{QA.openTripLog('lifetime','roadScreen')}],['arrival',()=>{QA.fixture({ended:false});QA.endGame('YOU MADE IT','WELCOME HOME.','The journey worked.')}],['failure',()=>{QA.fixture({ended:false,stats:QA.blankTripStats()});QA.endGame('STRANDED','THE ROAD GOES ON WITHOUT YOU.','You ran out of fuel.')}]];
 for(const [orientation,size] of [['portrait',{width:390,height:844}],['landscape',{width:844,height:390}]]){await page.setViewportSize(size);for(const [name,fn] of screenPlan){await page.evaluate(fn);await capture(page,name+'-'+orientation)}}
 // Full playthroughs use UI controls only; no state injection or synthetic results.
 await context.clearCookies();await page.evaluate(()=>localStorage.clear());await page.goto(url);await page.setViewportSize({width:390,height:844});await doRun(page,false);await capture(page,'success-run-ending');await page.click('#endTripReportBtn');await capture(page,'success-final-report');const lifetime=await page.evaluate(()=>QA.loadLifetime());ok('successful run counted exactly once',lifetime.runs===1&&lifetime.successes===1);await page.reload();await page.click('#resumeBtn');ok('completed run resumes final report without recounting',await page.evaluate(()=>QA.loadLifetime().runs===1));await doRun(page,true);await capture(page,'failure-run-ending');ok('failure lifetime accounting',await page.evaluate(()=>QA.loadLifetime().runs===2&&QA.loadLifetime().failures===1));
 ok('no JavaScript runtime exceptions',log.errors.length===0);
 fs.writeFileSync(path.join(results,'browser-qa.json'),JSON.stringify(log,null,2));await browser.close();server.close();console.log(JSON.stringify({checks:log.checks.length,screens:log.screens.length,runs:log.runs.map(r=>({type:r.type,miles:r.stats.milesDriven,ending:r.ending.kicker})),errors:log.errors}));
})().catch(e=>{log.errors.push(e.stack);fs.writeFileSync(path.join(results,'browser-qa.json'),JSON.stringify(log,null,2));console.error(e);server.close();process.exit(1)});
